services:
  proxy-1:
    image: ubuntu/squid:latest
    restart: always
    volumes:
      - ./proxy-config-1.conf:/etc/squid/squid.conf
      - ./htpasswd/proxy-1-user:/etc/squid/passwords
      - ./certs:/etc/squid/certs

  proxy-2:
    image: ubuntu/squid:latest
    restart: always
    volumes:
      - ./proxy-config-2.conf:/etc/squid/squid.conf
      - ./htpasswd/proxy-2-user:/etc/squid/passwords
      - ./certs:/etc/squid/certs

  app:
    build:
      context: .
    volumes:
      - ./results:/src/results/
    environment:
      proxy-1: proxy-1
      proxy-2: proxy-2
    depends_on:
      - proxy-1
      - proxy-2
